spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://${DB_CONNECTION_IP}:5432/postgres
    url: jdbc:postgresql://localhost:5437/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9090


private:
  key: QuwseOVacwFrOx2OjbsOmG1SKncnMPpFTQ0Dam2L/i4
